name: Release to crates.io

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  publish-ruby-structs:
    name: Publish rbspy-ruby-structs crate
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@4305c38b25d97ef35a8ad1f985ccf2d2242004f2 # stable branch
      - name: publish ruby-structs crate
        continue-on-error: true
        run: |
          cargo login ${{ secrets.CARGO_TOKEN }}
          cd ruby-structs
          cargo publish
  publish-rbspy:
    name: Publish rbspy crate
    needs: [publish-ruby-structs]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@4305c38b25d97ef35a8ad1f985ccf2d2242004f2 # stable branch
      - name: publish rbspy crate
        run: |
          cargo login ${{ secrets.CARGO_TOKEN }}
          cargo publish
